### ISSUE TITLE
#1. Big Bug

### ISSUE THREAD

**Issue by matthew4444** [UniversalMine/BigDrother#1]
# 1. Fix server not reciveing player packets(meaning player cant place or break blocks):
5
```yaml
6
Notice: Uninitialized string offset: 19 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110
7
[Receive from MatthewJP] 0x8

**Comment by matthew4444** [comment]
# 1. Fix server not reciveing player packets(meaning player cant place or break blocks):
5
```yaml
6
Notice: Uninitialized string offset: 19 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110
7
[Receive from MatthewJP] 0x8

**Comment by matthew4444** [comment]
1. Fix server not reciveing player packets(meaning player cant place or break blocks):

5

6
Notice: Uninitialized string offset: 19 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110
7
[Receive from MatthewJP] 0x8

**Comment by matthew4444** [comment]
# 1. Fix server not reciveing player packets(meaning player cant place or break blocks):
5
```yaml
6
Notice: Uninitialized string offset: 19 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110
7
[Receive from MatthewJP] 0x8

**Comment by matthew4444** [comment]
when will this bug be fixed? im thinking that this project isnt going anywhere, if this bug doesnt be fixed, sorry, plz fix soon, bye :(

**Comment by matthew4444** [comment]
hello? I know ur working on ur own projects, but I need help , with this last bug pl

**Comment by matthew4444** [comment]
plz?

**Comment by matthew4444** [comment]
@RedstoneAlmeida did u fix the bug?

**Comment by matthew4444** [comment]
NEW BUG 
Notice: Uninitialized string offset: 19 in phar://C:/Users/mmm26/Downloads/genisys/plugins/BigDrother.phar/src/shoghicp/BigBrother/network/Packet.php on line 110
[Receive from MatthewJP] 0x8

**Comment by matthew4444** [comment]
HELP PLZ

**Comment by RedstoneAlmeida** [comment]
is not simply fix packet bug

**Comment by matthew4444** [comment]
?? can u fix it plz, try plz, i dont want this project to die

**Comment by matthew4444** [comment]
:(

**Comment by DavidBrockway** [comment]
Hello i am back i can help you out

**Comment by DavidBrockway** [comment]
create  a chatroom on github vahtroom

**Comment by matthew4444** [comment]
which platform for chat room? gitter?

**Comment by DavidBrockway** [comment]
yes nvite me

**Comment by matthew4444** [comment]
ok, im in america , so i thought ud resppond way later, ill give aq link in a couple of mins ,and ill invite u, let me make the chat, it was 6 am when i latest chatted sorry about that, let me get started :)

**Comment by matthew4444** [comment]
ur invited https://gitter.im/UniversalMine-MP/Lobby :)

**Comment by matthew4444** [comment]
NEW BUG
Notice: Uninitialized string offset: 19 in phar://C:/Users/mmm26/Downloads/genisys/plugins/BigDrother.phar/src/shoghicp/BigBrother/network/Packet.php on line 110
[Receive from MatthewJP] 0x8 , this project is going to be dead soon :(

**Comment by Driesboy** [comment]
use the new bigbrother
