### ISSUE TITLE
Still can not install

### ISSUE THREAD

**Issue by HittmanA** [UniversalMine/BigDrother#2]
i nned help running the installer?
Nvm,fixed it.

**Comment by matthew4444** [comment]
ok , let me try a non modiifed install.sh

**Comment by matthew4444** [comment]
download install.sh and open it in ur mac terminal,

**Comment by matthew4444** [comment]
https://github.com/clodeacc/Genisys-Install

**Comment by HittmanA** [comment]
for reference here was the error:
```
Austins-MacBook-Air:UniversalMine-PC-master austinhitt$ ./start.sh
Failed loading /Users/Intyre/git/github.com/PocketMine/php7-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  dlopen(/Users/Intyre/git/github.com/PocketMine/php7-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so, 9): image not found

Warning: require_once(/Users/austinhitt/Desktop/UniversalMine-MP Mac,linux installer/UniversalMine-PC-master/src/spl/ClassLoader.php): failed to open stream: No such file or directory in /Users/austinhitt/Desktop/UniversalMine-MP Mac,linux installer/UniversalMine-PC-master/src/pocketmine/PocketMine.php on line 107

Fatal error: require_once(): Failed opening required '/Users/austinhitt/Desktop/UniversalMine-MP Mac,linux installer/UniversalMine-PC-master/src/spl/ClassLoader.php' (include_path='.:') in /Users/austinhitt/Desktop/UniversalMine-MP Mac,linux installer/UniversalMine-PC-master/src/pocketmine/PocketMine.php on line 107
```

**Comment by matthew4444** [comment]
create a new folder in ur downloads called server01

**Comment by HittmanA** [comment]
k

**Comment by HittmanA** [comment]
what now?

**Comment by matthew4444** [comment]
then download install.sh from here https://github.com/clodeacc/Genisys-Install/raw/master/install.sh
and then move it to the server01 folder, and open a termnal and run install.sh in the server 01 folder

**Comment by HittmanA** [comment]
ok i did

**Comment by matthew4444** [comment]
what do u see? in ther termanl

**Comment by HittmanA** [comment]
It installed. But there is no src folder. Only start.sh, install_log, bin, install.sh

**Comment by matthew4444** [comment]
ok, ill send u a new src folder, give me a min

**Comment by HittmanA** [comment]
thx

**Comment by HittmanA** [comment]
the main problem is that my src had no /spl/ folder

**Comment by matthew4444** [comment]
copy the src folder from here into the server 01 folder you created https://github.com/iTXTech/Genisys/archive/mcpe-1.0.zip

**Comment by matthew4444** [comment]
Did u copy the SRC?

**Comment by HittmanA** [comment]
Yes

**Comment by matthew4444** [comment]
So open the start.sh and tell me what happens plz

**Comment by HittmanA** [comment]
i get
```
Austins-MacBook-Air:UMM austinhitt$ ./start.sh
Failed loading /Users/Intyre/git/github.com/PocketMine/php7-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  dlopen(/Users/Intyre/git/github.com/PocketMine/php7-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so, 9): image not found

Warning: require_once(/Users/austinhitt/Desktop/UMM/src/spl/ClassLoader.php): failed to open stream: No such file or directory in /Users/austinhitt/Desktop/UMM/src/pocketmine/PocketMine.php on line 107

Fatal error: require_once(): Failed opening required '/Users/austinhitt/Desktop/UMM/src/spl/ClassLoader.php' (include_path='.:') in /Users/austinhitt/Desktop/UMM/src/pocketmine/PocketMine.php on line 107
```
Where is the spa folder?!

**Comment by matthew4444** [comment]
idk whats wrong on ur end, im looking at the spl folder in my micro pc?? https://github.com/iTXTech/Genisys/tree/mcpe-1.0/src

**Comment by matthew4444** [comment]
i have a solution

**Comment by HittmanA** [comment]
SPL not SRC

**Comment by matthew4444** [comment]
yes it says spl here, find the word spl:  This repository
Pull requests
Issues
Gist
 @matthew4444
 Watch 159
  Star 420
 Fork 337 iTXTech/Genisys
 Code  Issues 28  Pull requests 1  Projects 0  Wiki  Pulse  Graphs
Branch: mcpe-1.0  Create new file Upload files Find file History Genisys/src/
 Pull request   Compare This branch is 107 commits ahead, 2 commits behind master.
Latest commit 07dc3d6  13 hours ago @dktapps dktapps Shut PhpStorm up
..		
pocketmine	Shut PhpStorm up	12 hours ago
raklib @ f4bfcb8	Use pmmp/RakLib submodule	3 days ago
PS ITS HERE:  spl @ 23ac7b8	Fixed CommandReader hanging on shutdown, close pmmp/PocketMine-MP#25 (p…	3 days ago
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help

**Comment by matthew4444** [comment]
HERES AN EAISER OPTION http://goo.gl/xZlfT4

**Comment by matthew4444** [comment]
HERES AN EAISER OPTION http://goo.gl/xZlfT4

**Comment by HittmanA** [comment]
That just installs a pocketmine.phar

**Comment by matthew4444** [comment]
try this then

**Comment by matthew4444** [comment]
https://github.com/PrimusLV/PM-Installer/blob/master/pmInstall.sh

**Comment by matthew4444** [comment]
does that work?

**Comment by HittmanA** [comment]
I finally got it installed

**Comment by HittmanA** [comment]
I had to copy the src genysis spl folder

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Yay

**Comment by HittmanA** [comment]
What happened to the UniversalMine server software? Did we discontinue that?

**Comment by matthew4444** [comment]
i did, because noone was updating it and it was not where it was supsota be ,and it was confeusing me a lot, we usimng a plugin port with the last changes saved, just needs to be fixed of a main bug, nad its in the issues section,i gtg , i have school tommorow, bye, have a great night :)
